package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"

	"sms-backend/config"
	_ "sms-backend/docs" // generated by: swag init
	"sms-backend/models"
	"sms-backend/routes"
)

// @title           SMS Backend API
// @version         1.1
// @description     School Management System — Go + Gin + PostgreSQL
// @description
// @description     ## Authentication
// @description     This API uses JWT Bearer tokens. Login via `POST /api/login` to receive an access token (1 hour) and a refresh token (7 days).
// @description     Click the **Authorize** button above and enter: `Bearer <your_token>`
// @description
// @description     ## Roles
// @description     | Role    | Access                                              |
// @description     |---------|-----------------------------------------------------|
// @description     | Admin   | Full access to all endpoints                        |
// @description     | Teacher | Attendance, grades, locker (read public)             |
// @description     | Student | Own grades, report card, locker, finance             |
// @description     | Parent  | Children's data, report cards, finance               |

// @host            localhost:8080
// @BasePath        /

// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
// @description     Type "Bearer" followed by a space and your JWT token. Example: **Bearer eyJhbGci...**
func main() {
	if err := godotenv.Load(); err != nil {
		log.Fatal("Error loading .env file")
	}

	// FIX #7: Fail fast if JWT secrets are missing.
	// An empty secret signs tokens with "" which is trivially forgeable.
	// Never allow the server to start without required secrets.
	for _, envVar := range []string{"JWT_SECRET", "JWT_REFRESH_SECRET"} {
		if os.Getenv(envVar) == "" {
			log.Fatalf("FATAL: required environment variable %s is not set — server will not start", envVar)
		}
	}

	config.ConnectDB()

	// PreMigrate applies idempotent schema fixups (e.g. safe constraint drops)
	// that must run before AutoMigrate to avoid SQLSTATE 42704 errors when a
	// constraint exists under a different name or was never created.
	if err := config.PreMigrate(config.DB); err != nil {
		log.Fatal("Pre-migration failed: ", err)
	}

	err := config.DB.AutoMigrate(
		&models.User{},
		&models.Class{},
		&models.Subject{},
		&models.Student{},
		&models.Teacher{},
		&models.Enrollment{},
		&models.Attendance{},
		&models.Grade{},
		&models.LockerFile{},
		&models.Transaction{},
		&models.Payroll{},
		&models.Notification{},
		&models.NotificationReceipt{},
		&models.RefreshToken{},
	)
	if err != nil {
		log.Fatal("Migration failed: ", err)
	}
	log.Println("All tables migrated successfully")

	// FIX #15: Respect UPLOAD_DIR env var — same default as locker_ctrl.go's getUploadDir().
	uploadDir := os.Getenv("UPLOAD_DIR")
	if uploadDir == "" {
		uploadDir = "./uploads/locker"
	}
	if err := os.MkdirAll(uploadDir, 0750); err != nil {
		log.Fatal("Failed to create uploads directory: ", err)
	}

	r := gin.Default()
	r.SetTrustedProxies(nil)

	routes.SetupRoutes(r)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("SMS server running on :%s\n", port)
	log.Printf("Swagger UI:        http://localhost:%s/swagger/index.html\n", port)
	log.Printf("Custom Docs:       http://localhost:%s/docs\n", port)
	log.Printf("Notifications page: http://localhost:%s/notifications\n", port)

	if err := r.Run(":" + port); err != nil {
		log.Fatal("Server failed to start: ", err)
	}
}
