package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"

	"sms-backend/config"
	_ "sms-backend/docs" // generated by: swag init
	"sms-backend/models"
	"sms-backend/routes"
)

// @title           SMS Backend API
// @version         1.0
// @description     School Management System — Go + Gin + PostgreSQL
// @description
// @description     ## Authentication
// @description     This API uses JWT Bearer tokens. Login via `POST /api/login` to receive an access token (1 hour) and a refresh token (7 days).
// @description     Click the **Authorize** button above and enter: `Bearer <your_token>`
// @description
// @description     ## Roles
// @description     | Role    | Access                                              |
// @description     |---------|-----------------------------------------------------|
// @description     | Admin   | Full access to all endpoints                        |
// @description     | Teacher | Attendance, grades, locker (read public)             |
// @description     | Student | Own grades, report card, locker, finance             |
// @description     | Parent  | Children's data, report cards, finance               |

// @host            localhost:8080
// @BasePath        /

// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
// @description     Type "Bearer" followed by a space and your JWT token. Example: **Bearer eyJhbGci...**
func main() {
	if err := godotenv.Load(); err != nil {
		log.Fatal("Error loading .env file")
	}

	config.ConnectDB()

	err := config.DB.AutoMigrate(
		&models.User{},
		&models.Class{},
		&models.Subject{},
		&models.Student{},
		&models.Teacher{},
		&models.Enrollment{},
		&models.Attendance{},
		&models.Grade{},
		&models.LockerFile{},
		&models.Transaction{},
		&models.Payroll{},
	)
	if err != nil {
		log.Fatal("Migration failed: ", err)
	}
	log.Println("All tables migrated successfully")

	if err := os.MkdirAll("./uploads/locker", 0750); err != nil {
		log.Fatal("Failed to create uploads directory: ", err)
	}

	r := gin.Default()
	r.SetTrustedProxies(nil)

	routes.SetupRoutes(r)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("SMS server running on :%s\n", port)
	log.Printf("Swagger UI:  http://localhost:%s/swagger/index.html\n", port)
	log.Printf("Custom Docs: http://localhost:%s/docs\n", port)

	if err := r.Run(":" + port); err != nil {
		log.Fatal("Server failed to start: ", err)
	}
}
